version: '3'

x-app: &app
  build:
    dockerfile: docker/Dockerfile
    context: .
    args:
      - SYNC_ARGS=--without dev --sync
    target: base
  image: feeds_for_sendcloud_django
  env_file:
    - ./docker/envs/.django
    - ./docker/envs/.postgres

services:
    django:
      <<: *app
      depends_on:
        - postgres
        - redis
      entrypoint: ["./scripts/start.sh"]
      ports:
        - "8000:8000"

    postgres:
      image: postgres:13.13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - postgres_data_backups:/backups
      env_file:
        - ./docker/envs/.postgres

    redis:
      image: redis:7.0-alpine

    celery-worker:
      <<: *app
      depends_on:
        - django
        - redis
      restart: on-failure
      entrypoint: ["./scripts/celery.sh"]

    celery-beat:
      <<: *app
      depends_on:
        - django
      restart: on-failure
      entrypoint: ["./scripts/celery_beat.sh"]

    flower:
      <<: *app
      ports:
        - "5555:5555"
      depends_on:
        - django
        - redis
      entrypoint: ["./scripts/flower.sh"]

volumes:
  postgres_data: {}
  postgres_data_backups: {}

