# Generated by Django 4.0.8 on 2023-11-15 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("source", models.URLField(db_index=True, max_length=500, unique=True)),
                ("last_refresh", models.DateTimeField(default=None, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("processing", "processing"),
                            ("updated", "updated"),
                            ("failed", "failed"),
                            ("invalid", "invalid"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("source_err", models.JSONField(default=dict)),
                ("followers", models.ManyToManyField(related_name="feeds", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="feeds.feed"
                    ),
                ),
                ("users", models.ManyToManyField(related_name="read_posts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["link", "title"], name="feeds_post_link_d216ae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("link", "feed")},
        ),
    ]
